import { motion } from 'framer-motion'
import { closing } from '../data/homeContent'
import Button from './ui/Button'
import { skipInitialAnimation, useStartLoopAfterMount } from '../utils/hydrationFlag'

export default function ClosingCta() {
  const loopReady = useStartLoopAfterMount()
  const loop = (keyframes) => (loopReady ? keyframes : {})
  return <section className="px-5 py-24 lg:px-8 lg:py-32"><motion.div initial={skipInitialAnimation ? false : { opacity: 0, scale: 0.97 }} animate={skipInitialAnimation ? { opacity: 1, scale: 1 } : undefined} whileInView={skipInitialAnimation ? undefined : { opacity: 1, scale: 1 }} viewport={{ once: true, amount: 0.35 }} transition={{ duration: 0.6 }} className="relative mx-auto max-w-5xl overflow-hidden rounded-[2rem] bg-dolphin-600 px-6 py-16 text-center text-white shadow-2xl shadow-dolphin-900/20 sm:px-12"><motion.span initial={{ scale: 1, opacity: 0.18 }} animate={loop({ scale: [1, 1.18, 1], opacity: [0.18, 0.3, 0.18] })} transition={{ duration: 6, repeat: Infinity, ease: 'easeInOut' }} className="absolute -right-20 -top-20 h-64 w-64 rounded-full border-[48px] border-white" aria-hidden="true" data-loop-anim="true" data-rest-opacity="0.18" data-rest-transform="none" /><motion.span initial={{ scale: 1.1, opacity: 0.12 }} animate={loop({ scale: [1.1, 1, 1.1], opacity: [0.12, 0.22, 0.12] })} transition={{ duration: 7, repeat: Infinity, ease: 'easeInOut' }} className="absolute -bottom-24 -left-20 h-64 w-64 rounded-full border-[48px] border-white" aria-hidden="true" data-loop-anim="true" data-rest-opacity="0.12" data-rest-transform="scale(1.1)" /><div className="relative"><p className="text-xs font-bold tracking-[0.2em] text-white">READY WHEN YOU ARE</p><h2 className="mt-5 text-balance text-4xl font-extrabold lg:text-5xl">{closing.title}</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-white">{closing.body}</p><Button to="/contact-us" variant="light" className="mt-8">{closing.cta}</Button></div></motion.div></section>
}
